INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Windows)

SET(CMAKE_C_COMPILER clang.exe)
SET(CMAKE_CXX_COMPILER clang.exe)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
